# n = int(input("Enter N: "))
# arr = list(map(int, input().split()))
# arr.sort()
# print(arr[2])
# n = int(input("Enter N: "))
# arr = list(map(int, input().split()))
# arr.sort()
# for i in range(n):
#     print(arr[i])
# print("3rd element is:")
# print(arr[2])
